apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-atlassian
  # namespace applied at apply time
type: Opaque
data:
  DB_USERNAME: dXNlcg==        # base64("user")
  DB_PASSWORD: cGFzcw==        # base64("pass")
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret-atlassian
  # namespace applied at apply time
type: Opaque
data:
  REDIS_PASSWORD: cGFzc3dvcmQ=  # base64("password")
