apiVersion: batch/v1
kind: Job
metadata:
  name: zilla-migrations
  namespace: hybrid-grouped
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: hatch33/zilla-migrations:latest
          imagePullPolicy: Always
          env:
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: "dbchangelog.xml"
            - name: LIQUIBASE_COMMAND_UPDATE_URL
              value: "jdbc:postgresql://postgres:5450/zilla"
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-datadog
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-datadog
                  key: DB_PASSWORD
            - name: LIQUIBASE_LOG_LEVEL
              value: "info"
          workingDir: /liquibase/changelog
          command: ["liquibase"]
          args: ["update"]
      restartPolicy: Never
