apiVersion: v1
kind: Namespace
metadata:
  name: hybrid-grouped
  labels:
    zilla.io/model: grouped
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hybrid-grouped
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    zilla.io/model: grouped
type: Opaque
data:
  DB_USERNAME: dXNlcg==
  DB_PASSWORD: cGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: hybrid-grouped
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    zilla.io/model: grouped
type: Opaque
data:
  REDIS_PASSWORD: cGFzc3dvcmQ=
