# =====================
# Postgres Secret
# =====================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USERNAME: d1E1V1FOc3dFSEdCdzVzUUdHU1I=  # base64 encoded "wQ5WQNswEHGBw5sQGGSR"
  DB_PASSWORD: bUNVbnZHdG91YjFCSnBPcTBYWW8=  # base64 encoded "mCUnvGtoub1BJpOq0XYo"
---
# =====================
# Redis Secret
# =====================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: M2FEdVVMdDJhZnFOME9uOFpBcGY=  # base64 encoded "3aDuULt2afqN0On8ZApf"
---
