apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USERNAME: dXNlcg==
  DB_PASSWORD: cGFzcw==
  APP_DB_USERNAME: dGVuYW50
  APP_DB_PASSWORD: dGVuYW50cGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: cGFzc3dvcmQ=
