# =====================
# Postgres
# =====================
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5450
      targetPort: 5450
  selector:
    app: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: "zilla"
            - name: PGPORT
              value: "5450"
          ports:
            - containerPort: 5450
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      resources:
        requests:
          cpu: "1"
          memory: "1536Mi"
---
# =====================
# Redis
# =====================
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
          ports:
            - containerPort: 6379

---
# =====================
# Zilla Backend
# =====================
apiVersion: v1
kind: Service
metadata:
  name: zilla-backend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: zilla-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilla-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zilla-backend
  template:
    metadata:
      labels:
        app: zilla-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 postgres 5450; do echo "Waiting for Postgres..."; sleep 5; done;']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 redis 6379; do echo "Waiting for Redis..."; sleep 5; done;']
      containers:
        - name: zilla-backend
          image: hatch33/zilla-backend:v1.0.0-iso
          imagePullPolicy: Always
          command: ["npm", "run", "start:prod-local"]
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5450"
            - name: DB_NAME
              value: "zilla"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              value: "secret"
            - name: JWT_EXPIRES_IN_IN_SECONDS
              value: "100000"
            - name: NODE_ENV
              value: "test"
            - name: ADMIN_EMAL
              value: "urosvceh@gmail.com"
            - name: ADMIN_PASSWORD
              value: "pass123!"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: DB_POOL_MAX
              value: "100"
          ports:
            - containerPort: 3000
      resources:
        requests:
          cpu: "0.25"
          memory: "128Mi"
        limits:
          memory: "160Mi"
      

---
# =====================
# Nginx BFF Config
# =====================
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location /api/ {
            proxy_pass http://zilla-backend:3000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://zilla-frontend:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

---
# =====================
# Nginx BFF Service
# =====================
apiVersion: v1
kind: Service
metadata:
  name: nginx-bff
spec:
  selector:
    app: nginx-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# =====================
# Nginx BFF Deployment
# =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-bff
  template:
    metadata:
      labels:
        app: nginx-bff
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
# =====================
# Zilla Frontend
# =====================
apiVersion: v1
kind: Service
metadata:
  name: zilla-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: zilla-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilla-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zilla-frontend
  template:
    metadata:
      labels:
        app: zilla-frontend
    spec:
      containers:
        - name: zilla-frontend
          image: hatch33/zilla-frontend:v1.0.0-iso
          imagePullPolicy: Always
          command: ["npm", "run", "start"]
          env:
            - name: PORT
              value: "8080"
            - name: NGINX_URL
              value: "/api"
          ports:
            - containerPort: 8080

---
# =====================
# Liquibase Migrations (Job)
# =====================
apiVersion: batch/v1
kind: Job
metadata:
  name: zilla-migrations
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: hatch33/zilla-migrations:latest
          imagePullPolicy: Always
          env:
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: "dbchangelog.xml"
            - name: LIQUIBASE_COMMAND_UPDATE_URL
              value: "jdbc:postgresql://postgres:5450/zilla"
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: LIQUIBASE_LOG_LEVEL
              value: "info"
          workingDir: /liquibase/changelog
          command: ["liquibase"]
          args: ["update"]
      restartPolicy: Never
