# =====================
# Postgres Secret
# =====================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USERNAME: dXNlcg==  # base64 encoded "user"
  DB_PASSWORD: cGFzcw==  # base64 encoded "pass"
---
# =====================
# Redis Secret
# =====================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
---