apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      zilla.io/model: grouped
      zilla.io/group: iso
    includeSelectors: true
    includeTemplates: true
